### ISSUE TITLE
Watching the filesystem example: debounce skips events

### ISSUE THREAD

**Issue by c-antin** [denoland/denobyexample#109]
The debounce example [here](https://examples.deno.land/watching-files) is somewhat misleading.
There is a chance that events get skipped, because debounce aborts prior function calls.

A better approach would be to collect the events:
```ts
import { debounce } from "https://deno.land/std@0.174.0/async/debounce.ts";

const collector: Deno.FsEvent[] = [];
const collectDebounce = debounce(() => {
  const events = collector.splice(0, Infinity);
  console.log(events);
}, 2000);
const collect = (event: Deno.FsEvent) => {
  collector.push(event);
  collectDebounce();
};

const watcher = Deno.watchFs("./");

for await (const event of watcher) {
  collect(event);
}

```

This affects the following examples:
https://examples.deno.land/watching-files
https://deno.land/std@0.174.0/async/debounce.ts?s=debounce#example_0

**Comment by kt3k** [comment]
The events from `Deno.watchFs` are usually very verbose. I think the existing example is fine because this is what most users of `Deno.watchFs` need to do.

(For example, single file save generates 3 events with the same payload (at least on my machine). Most users probably would want to ignore first 2 events.)
